repos:
  - repo: local
    hooks:
      - id: tests
        name: tests
        entry: Rscript -e "testthat::test_local('.')"
        language: system
        always_run: true
        pass_filenames: false
