test_that("snp_types works", {
    expect_length(allowed_vals_single, 11)
    expect_length(allowed_vals_double, 17)
    expect_length(iupac_map, 17)
    expect_named(iupac_map)
    expect_false(all(duplicated(allowed_vals_single)))
    expect_false(all(duplicated(allowed_vals_double)))
    expect_false(all(duplicated(iupac_map)))
    expect_type(allowed_vals_single, "character")
    expect_type(allowed_vals_double, "character")
    expect_type(iupac_map, "character")
    expect_type(names(iupac_map), "character")
})